#!/usr/bin/env python
# coding: utf-8

# # Training FakeVideoDetection Pipeline

import sys
import os
sys.path.append(os.path.abspath("src"))

import torch
import torch.nn as nn
import torch.optim as optim
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader, WeightedRandomSampler
from models.fusion import MultiModalFusionModel
from data.dataset import FakeVideoDataset
from sklearn.metrics import f1_score, roc_auc_score
from collections import Counter
from tqdm import tqdm
import numpy as np

# ─────────────────────────────────────────────
# Environment: reduce CUDA fragmentation
# ─────────────────────────────────────────────
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

# ─────────────────────────────────────────────
# GPU Selection — pick the GPU with most free memory
# Uses nvidia-smi so it sees ALL users' processes, not just ours.
# ─────────────────────────────────────────────
def _pick_best_gpu():
    """Return the GPU index with the most free memory (via nvidia-smi), or 0."""
    if not torch.cuda.is_available():
        return None
    n = torch.cuda.device_count()
    try:
        import subprocess
        result = subprocess.run(
            ["nvidia-smi",
             "--query-gpu=index,memory.free,memory.total,name",
             "--format=csv,noheader,nounits"],
            capture_output=True, text=True, timeout=10
        )
        free_mem = {}
        for line in result.stdout.strip().splitlines():
            idx, free, total, name = [x.strip() for x in line.split(",")]
            idx = int(idx)
            free_mb = int(free)
            total_mb = int(total)
            print(f"  GPU {idx} [{name}]: {free_mb} MiB free / {total_mb} MiB total")
            free_mem[idx] = free_mb
        best = max(free_mem, key=free_mem.get)
        print(f"  → Selected GPU {best} ({free_mem[best]} MiB free)")
        return best
    except Exception as e:
        print(f"  [WARN] nvidia-smi failed ({e}), defaulting to GPU 0")
        return 0

print("CUDA Available:", torch.cuda.is_available())
best_gpu = _pick_best_gpu()
device = torch.device(f"cuda:{best_gpu}" if best_gpu is not None else "cpu")
torch.cuda.set_device(device)
print(f"Using device: {device} — {torch.cuda.get_device_name(device)}")

# ─────────────────────────────────────────────
# GPU Memory Monitor helper
# ─────────────────────────────────────────────
def print_gpu_memory(tag=""):
    if not torch.cuda.is_available():
        return
    alloc  = torch.cuda.memory_allocated(device) / 1024**3
    reserv = torch.cuda.memory_reserved(device)  / 1024**3
    total  = torch.cuda.get_device_properties(device).total_memory / 1024**3
    free   = total - reserv
    marker = " ⚠ LOW" if free < 4.0 else ""
    print(f"  GPU mem [{tag}]: allocated={alloc:.2f}G  "
          f"reserved={reserv:.2f}G  free≈{free:.2f}G{marker}")

# ─────────────────────────────────────────────
# H100 TF32 — faster matmuls, negligible precision loss
# ─────────────────────────────────────────────
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32       = True
torch.backends.cudnn.benchmark        = True   # auto-tunes CUDNN kernels

# ─────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────
torch.manual_seed(42)

csv_path   = "dataset/processed/metadata.csv"  # Generated by extract.py
BATCH_SIZE = 4           # Micro-batch per forward pass (OOM-safe)
ACCUM_STEPS = 4          # Gradient accumulation: effective batch = 4×4 = 16
NUM_FRAMES  = 8          # Reduced from 16 to halve per-sample GPU memory
NUM_WORKERS = 4
PIN_MEMORY  = True

# ─────────────────────────────────────────────
# Dataset & Splits
# ─────────────────────────────────────────────
dataset = FakeVideoDataset(csv_path, num_frames=NUM_FRAMES)
print(f"Total videos found: {len(dataset)}")

# ── Class balance check ──────────────────────
labels_all = [int(dataset.metadata.iloc[i]["label"]) for i in range(len(dataset))]
counts = Counter(labels_all)
print(f"Class distribution — Real(0): {counts[0]}, Fake(1): {counts[1]}")
total = counts[0] + counts[1]
imbalance_ratio = max(counts[0], counts[1]) / total
if imbalance_ratio > 0.8:
    print(f"⚠  WARNING: dataset is {imbalance_ratio*100:.1f}% majority class "
          f"— accuracy alone is misleading. Using weighted sampling + F1/AUC metrics.")

# ── Train / Val split ────────────────────────
train_size = int(0.8 * len(dataset))
val_size   = len(dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(
    dataset, [train_size, val_size],
    generator=torch.Generator().manual_seed(42)
)
print(f"Train: {train_size}  Val: {val_size}")

# ── Weighted sampler for class imbalance ─────
train_labels = [int(dataset.metadata.iloc[i]["label"])
                for i in train_dataset.indices]
class_counts  = Counter(train_labels)
class_weights = {cls: 1.0 / cnt for cls, cnt in class_counts.items()}
sample_weights = [class_weights[lbl] for lbl in train_labels]
sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE,
                          sampler=sampler,
                          num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE,
                          shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)

# ─────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────
model     = MultiModalFusionModel(vit_pretrained=True).to(device)
criterion = nn.BCEWithLogitsLoss()

# ── Enable gradient checkpointing on ViT to cut activation memory ──
# torchvision ViT uses sequential encoder blocks — wrap with checkpoint
from torch.utils.checkpoint import checkpoint_sequential
_orig_vit_forward = model.vit.vit.encoder.forward

def _checkpointed_vit_encoder_forward(self, x):
    layers = list(self.layers)
    x = checkpoint_sequential(layers, segments=len(layers) // 2,
                               input=x, use_reentrant=False)
    return self.ln(x)

import types
model.vit.vit.encoder.forward = types.MethodType(
    _checkpointed_vit_encoder_forward, model.vit.vit.encoder
)
print_gpu_memory("after model init")

# ─────────────────────────────────────────────
# Frame-Level Wrapper (Stage 1)
# ─────────────────────────────────────────────
class FrameLevelViT(nn.Module):
    """Trains the ViT backbone independently on single frames."""
    def __init__(self, vit_extractor, dropout=0.3):
        super().__init__()
        self.vit = vit_extractor
        self.classifier = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(self.vit.embed_dim, 1)
        )

    def forward(self, x):
        emb = self.vit(x)
        return self.classifier(emb)


# ─────────────────────────────────────────────
# Training / Eval helpers
# ─────────────────────────────────────────────
def train_epoch(model_obj, loader, optimizer, scaler, criterion_obj,
                device_obj, stage_name, is_frame_level=False,
                accum_steps=ACCUM_STEPS):
    model_obj.train()
    running_loss = 0.0
    correct = 0
    total   = 0
    all_labels = []
    all_probs  = []

    optimizer.zero_grad(set_to_none=True)
    pbar = tqdm(loader, desc=f"Training {stage_name}")

    for step, batch in enumerate(pbar):
        rgb   = batch["rgb"].to(device_obj, non_blocking=True)
        label = batch["label"].to(device_obj, non_blocking=True).unsqueeze(1)

        # ── Label Smoothing ───────────────────────
        smoothed_label = label * 0.9 + 0.05 # 1.0 -> 0.95, 0.0 -> 0.05
        
        # ── Gradient Accumulation ─────────────────
        # Divide loss by accum_steps so gradients average over the
        # effective batch (micro_batch × accum_steps) not just micro_batch.
        with autocast('cuda'):
            if is_frame_level:
                S = rgb.shape[1]
                frame_idx = torch.randint(0, S, (1,)).item()
                outputs = model_obj(rgb[:, frame_idx])
                loss = criterion_obj(outputs, smoothed_label) / accum_steps
            else:
                fft   = batch["fft"].to(device_obj, non_blocking=True)
                audio = batch["audio"].to(device_obj, non_blocking=True)
                audio_mask = batch.get("audio_missing")
                if audio_mask is not None:
                    audio_mask = audio_mask.to(device_obj, non_blocking=True)
                    
                outputs, embs = model_obj(rgb, fft, audio, audio_mask=audio_mask, return_embeddings=True)
                
                loss_bce = criterion_obj(outputs, smoothed_label)
                
                # Consistency Loss
                e_vid, e_fft, e_aud = embs
                cos = nn.CosineSimilarity(dim=-1)
                
                loss_consist = (1 - cos(e_vid, e_fft)).mean()
                if audio_mask is not None:
                    valid_audio = ~audio_mask
                    if valid_audio.any():
                        loss_consist += (1 - cos(e_vid[valid_audio], e_aud[valid_audio])).mean()
                else:
                    loss_consist += (1 - cos(e_vid, e_aud)).mean()
                    
                loss = (loss_bce + 0.1 * loss_consist) / accum_steps

        scaler.scale(loss).backward()

        is_update_step = ((step + 1) % accum_steps == 0) or (step + 1 == len(loader))
        if is_update_step:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model_obj.parameters(), max_norm=1.0)
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)
            # Free intermediate activations after each optimiser update
            torch.cuda.empty_cache()

        # ── Track metrics (use un-scaled loss for display) ──
        loss = loss * accum_steps  # rescale back for logging

        bs = label.size(0)
        running_loss += loss.item() * bs
        probs  = torch.sigmoid(outputs).detach()
        preds  = (probs > 0.5).float()
        correct += (preds == label).sum().item()
        total   += bs

        all_labels.extend(label.cpu().numpy().flatten().tolist())
        all_probs.extend(probs.cpu().numpy().flatten().tolist())

        # ── Per-batch metrics (not cumulative) ──
        pbar.set_postfix({
            "loss": f"{loss.item():.4f}",
            "acc":  f"{100.*correct/total:.2f}%"
        })

    epoch_loss = running_loss / total
    epoch_acc  = correct / total
    try:
        epoch_f1  = f1_score(all_labels, [p > 0.5 for p in all_probs], zero_division=0)
        epoch_auc = roc_auc_score(all_labels, all_probs) if len(set(all_labels)) > 1 else float("nan")
    except Exception:
        epoch_f1, epoch_auc = 0.0, float("nan")

    print(f"  [Train] loss={epoch_loss:.4f}  acc={100.*epoch_acc:.2f}%  "
          f"F1={epoch_f1:.4f}  AUC={epoch_auc:.4f}")
    return epoch_loss, epoch_acc, epoch_f1, epoch_auc


@torch.no_grad()
def evaluate(model_obj, loader, criterion_obj, device_obj, is_frame_level=False):
    model_obj.eval()
    running_loss = 0.0
    correct = 0
    total   = 0
    all_labels = []
    all_probs  = []

    pbar = tqdm(loader, desc="Evaluating", leave=False)
    for batch in pbar:
        rgb   = batch["rgb"].to(device_obj, non_blocking=True)
        label = batch["label"].to(device_obj, non_blocking=True).unsqueeze(1)

        with autocast('cuda'):
            if is_frame_level:
                S = rgb.shape[1]
                outputs = model_obj(rgb[:, S // 2])
            else:
                fft   = batch["fft"].to(device_obj, non_blocking=True)
                audio = batch["audio"].to(device_obj, non_blocking=True)
                audio_mask = batch.get("audio_missing")
                if audio_mask is not None:
                    audio_mask = audio_mask.to(device_obj, non_blocking=True)
                outputs = model_obj(rgb, fft, audio, audio_mask=audio_mask)

            loss = criterion_obj(outputs, label)

        bs = label.size(0)
        running_loss += loss.item() * bs
        probs  = torch.sigmoid(outputs)
        preds  = (probs > 0.5).float()
        correct += (preds == label).sum().item()
        total   += bs

        all_labels.extend(label.cpu().numpy().flatten().tolist())
        all_probs.extend(probs.cpu().numpy().flatten().tolist())

    val_loss = running_loss / total
    val_acc  = correct / total
    try:
        val_f1  = f1_score(all_labels, [p > 0.5 for p in all_probs], zero_division=0)
        val_auc = roc_auc_score(all_labels, all_probs) if len(set(all_labels)) > 1 else float("nan")
    except Exception:
        val_f1, val_auc = 0.0, float("nan")

    print(f"  [Val]   loss={val_loss:.4f}  acc={100.*val_acc:.2f}%  "
          f"F1={val_f1:.4f}  AUC={val_auc:.4f}")
    return val_loss, val_acc, val_f1, val_auc


# ─────────────────────────────────────────────
# Checkpointing helper
# ─────────────────────────────────────────────
os.makedirs("models", exist_ok=True)

def save_checkpoint(model_obj, optimizer, epoch, val_loss, path):
    torch.save({
        "epoch":      epoch,
        "model":      model_obj.state_dict(),
        "optimizer":  optimizer.state_dict(),
        "val_loss":   val_loss,
    }, path)
    print(f"  ✓ Checkpoint saved: {path}")


# ─────────────────────────────────────────────
# STAGE 1 — Train ViT backbone (frame-level)
# ─────────────────────────────────────────────
epochs_s1 = 3
best_val_loss_s1 = float("inf")
patience_s1 = 2
no_improve_s1 = 0

print("\n" + "="*60)
print("STAGE 1: Train ViT (Frame-Level)")
print("="*60)

frame_model = FrameLevelViT(model.vit).to(device)
optimizer1 = optim.AdamW(frame_model.parameters(), lr=1e-4, weight_decay=1e-4)
scaler1    = GradScaler('cuda')

for epoch in range(epochs_s1):
    print(f"\n── S1 Epoch {epoch+1}/{epochs_s1} ──")
    train_epoch(frame_model, train_loader, optimizer1, scaler1,
                criterion, device, f"S1 Epoch {epoch+1}", is_frame_level=True)
    val_loss, *_ = evaluate(frame_model, val_loader, criterion, device, is_frame_level=True)

    if val_loss < best_val_loss_s1:
        best_val_loss_s1 = val_loss
        no_improve_s1 = 0
        save_checkpoint(frame_model, optimizer1, epoch, val_loss,
                        "models/best_stage1.pth")
    else:
        no_improve_s1 += 1
        if no_improve_s1 >= patience_s1:
            print(f"  Early stopping S1 at epoch {epoch+1}")
            break

    # Free cache between stages / epochs
    torch.cuda.empty_cache()
    print_gpu_memory(f"S1 epoch {epoch+1} end")


# ─────────────────────────────────────────────
# STAGE 2 — Freeze ViT, train temporal/FFT/audio
# ─────────────────────────────────────────────
epochs_s2 = 5
best_val_loss_s2 = float("inf")
patience_s2 = 3
no_improve_s2 = 0

print("\n" + "="*60)
print("STAGE 2: Freeze ViT, Train Temporal/Audio/FFT")
print("="*60)

for param in model.vit.parameters():
    param.requires_grad = False

optimizer2 = optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=1e-4, weight_decay=1e-4
)
scaler2 = GradScaler('cuda')

for epoch in range(epochs_s2):
    print(f"\n── S2 Epoch {epoch+1}/{epochs_s2} ──")
    train_epoch(model, train_loader, optimizer2, scaler2,
                criterion, device, f"S2 Epoch {epoch+1}", is_frame_level=False)
    val_loss, *_ = evaluate(model, val_loader, criterion, device, is_frame_level=False)

    if val_loss < best_val_loss_s2:
        best_val_loss_s2 = val_loss
        no_improve_s2 = 0
        save_checkpoint(model, optimizer2, epoch, val_loss,
                        "models/best_stage2.pth")
    else:
        no_improve_s2 += 1
        if no_improve_s2 >= patience_s2:
            print(f"  Early stopping S2 at epoch {epoch+1}")
            break

    torch.cuda.empty_cache()
    print_gpu_memory(f"S2 epoch {epoch+1} end")


# ─────────────────────────────────────────────
# STAGE 3 — Fine-tune full pipeline
# ─────────────────────────────────────────────
epochs_s3 = 5
best_val_loss_s3 = float("inf")
best_val_auc_s3  = 0.0
patience_s3 = 3
no_improve_s3 = 0

print("\n" + "="*60)
print("STAGE 3: Fine-Tune Full Multi-Modal Pipeline")
print("="*60)

for param in model.vit.parameters():
    param.requires_grad = True

# Lower LR for fine-tuning; use differential LR
optimizer3 = optim.AdamW([
    {"params": model.vit.parameters(),      "lr": 1e-5},
    {"params": model.temporal.parameters(), "lr": 5e-5},
    {"params": model.frequency.parameters(),"lr": 5e-5},
    {"params": model.audio.parameters(),    "lr": 5e-5},
    {"params": model.classifier.parameters(),"lr": 1e-4},
], weight_decay=1e-4)

scheduler3 = optim.lr_scheduler.CosineAnnealingLR(optimizer3, T_max=epochs_s3)
scaler3    = GradScaler('cuda')

for epoch in range(epochs_s3):
    print(f"\n── S3 Epoch {epoch+1}/{epochs_s3} ──")
    train_epoch(model, train_loader, optimizer3, scaler3,
                criterion, device, f"S3 Epoch {epoch+1}", is_frame_level=False)
    val_loss, val_acc, val_f1, val_auc = evaluate(
        model, val_loader, criterion, device, is_frame_level=False)

    scheduler3.step()

    # Save on best AUC (more meaningful than loss for imbalanced data)
    if val_auc > best_val_auc_s3:
        best_val_auc_s3 = val_auc
        no_improve_s3  = 0
        save_checkpoint(model, optimizer3, epoch, val_loss,
                        "models/best_stage3.pth")
    else:
        no_improve_s3 += 1
        if no_improve_s3 >= patience_s3:
            print(f"  Early stopping S3 at epoch {epoch+1}")
            break

    torch.cuda.empty_cache()
    print_gpu_memory(f"S3 epoch {epoch+1} end")


# ─────────────────────────────────────────────
# Save final model
# ─────────────────────────────────────────────
print("\nTraining Complete! Saving final multi-modal model...")
torch.save(model.state_dict(), "models/final_multimodal_model.pth")
print("Model saved to models/final_multimodal_model.pth")
